"""
PR Lifecycle Helpers
=====================

Branch creation, PR description generation, CI status parsing,
and merge readiness checks. Orchestrator calls these to build
PR-related actions.

Actual git/gh commands are executed by the SKILL.md (via Bash tool),
not by this module. This module builds the commands and checks conditions.
"""

import re


def build_branch_name(task: dict) -> str:
    """Build a git branch name from a task."""
    task_id = task.get("id", "task")
    desc = task.get("description", "feature")
    # Sanitize: lowercase, replace non-alnum with hyphens, collapse
    slug = re.sub(r"[^a-z0-9]+", "-", desc.lower()).strip("-")
    slug = slug[:40]  # Cap length
    return f"astra/{task_id}-{slug}"


def build_pr_description(task: dict) -> str:
    """Build a PR description from a task."""
    lines = [
        f"## {task.get('description', 'Feature')}",
        "",
        f"**Task:** `{task.get('id', 'unknown')}`",
        "",
    ]

    ac = task.get("acceptance_criteria", [])
    if ac:
        lines.append("### Acceptance Criteria")
        for criterion in ac:
            lines.append(f"- [ ] {criterion}")
        lines.append("")

    target_files = task.get("target_files", [])
    if target_files:
        lines.append("### Files Changed")
        for f in target_files:
            lines.append(f"- `{f}`")
        lines.append("")

    lines.append("---")
    lines.append("Generated by astra plugin")

    return "\n".join(lines)


def parse_ci_status(status: str) -> dict:
    """Parse a CI status string into a structured result."""
    status = status.strip().lower()

    if status in ("success", "passed", "passing"):
        return {"passed": True, "pending": False, "status": status}
    elif status in ("pending", "queued", "in_progress", "running"):
        return {"passed": False, "pending": True, "status": status}
    else:
        return {"passed": False, "pending": False, "status": status}


def check_merge_ready(
    config: dict,
    ci_passed: bool = False,
    approved: bool = False,
) -> dict:
    """Check if a PR is ready to merge based on config and status.

    Returns {ready: bool, reason: str}.
    """
    pr_config = config.get("pr", {})

    if not pr_config.get("enabled", False):
        return {"ready": False, "reason": "PR lifecycle disabled in config"}

    if not pr_config.get("auto_merge", False):
        return {"ready": False, "reason": "Auto-merge disabled — manual merge required"}

    if not ci_passed:
        return {"ready": False, "reason": "CI has not passed"}

    if not approved:
        return {"ready": False, "reason": "PR not approved"}

    return {"ready": True, "reason": "All checks passed"}
